#!/bin/sh
# This is a sample shell script showing how you can submit the ENABLE_NOTIFICATIONS command
# to Nagios.  Adjust variables to fit your environment as necessary.

now=`date +%s`
commandfile='/usr/local/nagios/var/rw/nagios.cmd'

/usr/bin/printf "[%lu] ENABLE_NOTIFICATIONS\n" $now > $commandfile
